# Generated by Django 6.0.3 on 2026-03-19 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('dentistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='configuracionagenda',
            unique_together={('dentista', 'dia_semana')},
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentistas.perfildentista')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentistas.perfildentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.paciente')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
                'unique_together': {('dentista', 'fecha', 'hora')},
            },
        ),
    ]
