# Generated by Django 6.0.3 on 2026-03-19 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_paciente_alter_configuracionagenda_unique_together_and_more'),
        ('dentistas', '0002_perfildentista_activo_perfildentista_color_principal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloquehorario',
            options={'ordering': ['fecha', 'hora_inicio']},
        ),
        migrations.AlterModelOptions(
            name='configuracionagenda',
            options={'ordering': ['dia_semana']},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='dentistas.perfildentista'),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Dejar vacío para bloquear el día completo', null=True),
        ),
        migrations.AlterField(
            model_name='configuracionagenda',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_agenda', to='dentistas.perfildentista'),
        ),
        migrations.AlterField(
            model_name='configuracionagenda',
            name='duracion_cita',
            field=models.IntegerField(default=30, help_text='Duración en minutos de cada cita'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='dentistas.perfildentista'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='agenda.paciente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'confirmada'])), fields=('dentista', 'fecha', 'hora'), name='unique_reserva_activa_por_dentista'),
        ),
    ]
