# Generated by Django 5.0.6 on 2026-09-12 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_reserva_recordatorio_2h'),
        ('dentistas', '0004_alter_perfildentista_color_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='recordatorio_2h_enviado',
        ),
        migrations.AddField(
            model_name='paciente',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='dentistas.perfildentista'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('dentista', 'email'), name='unique_paciente_email_por_dentista'),
        ),
    ]
