# Generated by Django 6.0.3 on 2026-03-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildentista',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfildentista',
            name='color_principal',
            field=models.CharField(default='#0F6E56', help_text='Color hex, ej: #0F6E56', max_length=7),
        ),
        migrations.AddField(
            model_name='perfildentista',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Texto que ve el paciente al entrar al perfil'),
        ),
        migrations.AddField(
            model_name='perfildentista',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perfildentista',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto del dentista', null=True, upload_to='dentistas/'),
        ),
        migrations.AddField(
            model_name='perfildentista',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo del consultorio', null=True, upload_to='logos/'),
        ),
    ]
