# Generated by Django 5.0.6 on 2026-09-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentistas', '0003_tema_imagen_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildentista',
            name='color_principal',
            field=models.CharField(default='#0d9e75', help_text='Color hex, ej: #0d9e75', max_length=7),
        ),
        migrations.AlterField(
            model_name='perfildentista',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfildentista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='dentistas/'),
        ),
        migrations.AlterField(
            model_name='perfildentista',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
